# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexbea.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
config:
  # Meta
  title: Alexander Bea # Your name will go here
  description: "Front end web developer" # used by search engines
  default_img: "img/ab-logo-min.png"

  # Header and footer text
  header_text: >
     <h2 class="h3">Front end web developer</h2>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with code. And love.

  # Icons
  rss: true
  email_address: "alex@abcreations.co" # Full email address
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "abea" # github profile name, e.g. "madebymunsters"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/alexbea" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "http://stackoverflow.com/users/888550/alexbea" # Full URL
  steam:
  tumblr:
  twitter: "alexbea"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-32705264-1"
  disqus_shortname: "alexbea"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "My RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Work+Sans:800"

# PAGINATION
# paginate: 10
# paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /work/:path/
  demos:
    output: true
    permalink: /demos/:path/

# BUILD SETTINGS
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

# GEMS
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - kramdown
  - rouge
